export const conteudosYoutube = [
    {
        id: 1,
        titulo: "Perspectivas 2026: os temas de RH que devem estar na pauta dos conselhos de administração",
        data: "30/01/2026",
        capa: "qegAIFMF7bI",
        url: "https://www.youtube.com/watch?v=qegAIFMF7bI",
    },
    {
        id: 2,
        titulo: "O Futuro da Saúde no Brasil: Longevidade, Acesso e Sustentabilidade",
        data: "28/03/2026",
        capa: "Yn2WBBxed04",
        url: "https://youtu.be/Yn2WBBxed04",
    },
    {
        id: 3,
        titulo: "Capatção de Investimentos em Startups",
        data: "17/06/2025",
        capa: "4z_avH842vs",
        url: "https://youtu.be/4z_avH842vs?list=PL98yzQXxvQjVDk60HdOp9dySACtnJErRO",
    },
    {
        id: 4,
        titulo: "O choque entre gerações: Desafios e oportunidades",
        data: "17/10/2025",
        capa: "q7B2JJcgAvY",
        url: "https://youtu.be/q7B2JJcgAvY",
    },
];

export const webinarYoutube = [
    {
        id: 1,
        titulo: "Webinar de Lançamento da ACB - Associação de Conselheiros do Brasil",
        destaque: "A ACB nasce com a missão de influenciar e transformar as empresas brasileiras, de todos os portes, por meio da Governança Corporativa. Se você é conselheiro ou deseja saber como podemos contribuir com a sua organização, venha nos conhecer melhor.",
        tag: "Webinar",
        capa: "tq-apY9biPM",
        url: "https://youtu.be/tq-apY9biPM?list=PL98yzQXxvQjWG900r7Kd4JzYuXnItBq5N",
    },
    {
        id: 2,
        titulo: "Webinar ESG Fundamental para Conselheiros",
        tag: "Webinar",
        capa: "F9jzJu_5Kp0",
        url: "https://youtu.be/F9jzJu_5Kp0?list=PL98yzQXxvQjWG900r7Kd4JzYuXnItBq5N",
    },
    {
        id: 3,
        titulo: "Webinar ESG Fundamental para Conselheiros",
        tag: "Webinar",
        capa: "bDTLTrVX4e4",
        url: "https://youtu.be/bDTLTrVX4e4?list=PL98yzQXxvQjWG900r7Kd4JzYuXnItBq5N",
    },
    {
        id: 4,
        titulo: "Novo Ano, Novo Governo, Novos Conselhos",
        tag: "Webinar",
        capa: "hsyAxyW6Xsc",
        url: "https://youtu.be/hsyAxyW6Xsc?list=PL98yzQXxvQjWG900r7Kd4JzYuXnItBq5N",
    },
    {
        id: 5,
        titulo: "Mulheres em Conselhos",
        tag: "Webinar",
        capa: "Dm6H_pn3HNE",
        url: "https://youtu.be/Dm6H_pn3HNE?list=PL98yzQXxvQjWG900r7Kd4JzYuXnItBq5N",
    },
    {
        id: 6,
        titulo: "Saudades das incertezas! Questões-chave para os conselheiros num cenário de contradições - Parte II",
        tag: "Webinar",
        capa: "bhO1fJJ4vnk",
        url: "https://youtu.be/bhO1fJJ4vnk?list=PL98yzQXxvQjWG900r7Kd4JzYuXnItBq5N",
    },
    {
        id: 7,
        titulo: "Conformidade: Como implementar em PMEs no contexto atual",
        tag: "Webinar",
        capa: "pkwUsKzRTdU",
        url: "https://youtu.be/pkwUsKzRTdU?list=PL98yzQXxvQjWG900r7Kd4JzYuXnItBq5N",
    },
    {
        id: 8,
        titulo: "O contexto da saúde suplementar e os efeitos na governança",
        tag: "Webinar",
        capa: "XB3maWo37m8",
        url: "https://youtu.be/XB3maWo37m8?list=PL98yzQXxvQjWG900r7Kd4JzYuXnItBq5N",
    },
    {
        id: 9,
        titulo: "Quem quer ser CEO: o desafio de atrair e desenvolver jovens para posições executivas",
        tag: "Webinar",
        capa: "KYXgV9edw-8",
        url: "https://youtu.be/KYXgV9edw-8?list=PL98yzQXxvQjWG900r7Kd4JzYuXnItBq5N",
    },
    {
        id: 10,
        titulo: "Verticalização x Terceirização: estratégias para as pequenas e médias empresas",
        tag: "Webinar",
        capa: "ATcUsrn5jp0",
        url: "https://youtu.be/ATcUsrn5jp0?list=PL98yzQXxvQjWG900r7Kd4JzYuXnItBq5N",
    },
    {
        id: 11,
        titulo: "Diversidade em conselhos",
        tag: "Webinar",
        capa: "whvxoZ450s4",
        url: "https://youtu.be/whvxoZ450s4?list=PL98yzQXxvQjWG900r7Kd4JzYuXnItBq5N",
    },
    {
        id: 12,
        titulo: "Pautas essenciais para os Conselhos em 2024",
        tag: "Webinar",
        capa: "CKihmr4dSa0",
        url: "https://youtu.be/CKihmr4dSa0?list=PL98yzQXxvQjWG900r7Kd4JzYuXnItBq5N",
    },
];
